# Generated by Django 5.1.2 on 2025-10-06 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_archive_delete_historiquemouvement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='date_soumission',
        ),
        migrations.RemoveField(
            model_name='file',
            name='date_validation',
        ),
        migrations.RemoveField(
            model_name='file',
            name='est_valide',
        ),
        migrations.RemoveField(
            model_name='file',
            name='notification_envoyee',
        ),
        migrations.RemoveField(
            model_name='file',
            name='rejetee',
        ),
        migrations.RemoveField(
            model_name='file',
            name='valide',
        ),
        migrations.RemoveField(
            model_name='file',
            name='valide_par',
        ),
    ]
