# Generated by Django 5.1.2 on 2025-10-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_file_date_soumission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
