# Generated by Django 5.1.2 on 2025-10-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_archive_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='archive',
            index=models.Index(fields=['owner', 'is_active'], name='api_archive_owner_i_49b071_idx'),
        ),
    ]
