# Generated by Django 5.1.2 on 2025-10-10 00:20

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('api', '0007_folder_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='fichier',
            field=models.FileField(upload_to='uploads/', null=True, blank=True),
        ),
    ]
