# Generated by Django 5.1.2 on 2025-10-10 10:58

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('api', '0008_auto_20251010_0020'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE api_file ALTER COLUMN fichier TYPE VARCHAR(255);",
            reverse_sql="ALTER TABLE api_file ALTER COLUMN fichier TYPE VARCHAR(100);",
        ),
    ]

