# Generated by Django 5.1.2 on 2025-10-11 23:55

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20251010_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.folder'),
        ),
        migrations.AlterField(
            model_name='file',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_to_folder),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('share', 'Partage de dossier'), ('permission', 'Mise à jour de permissions'), ('upload', 'Nouveau fichier'), ('archive', 'Archive disponible'), ('info', 'Information générale')], default='info', max_length=100),
        ),
    ]
