# Generated by Django 5.1.2 on 2026-06-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_service_fields_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
