# Generated by Django 5.1.2 on 2026-06-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_utilisateur_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='type_archive',
            field=models.CharField(default='zip', max_length=10),
        ),
    ]
