# Generated by Django 5.1.2 on 2026-06-26 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_archive_type_archive'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_log_id', models.IntegerField()),
                ('deleted_utilisateur', models.CharField(blank=True, max_length=150)),
                ('deleted_action', models.CharField(blank=True, max_length=20)),
                ('deleted_objet', models.CharField(blank=True, max_length=255)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_deletions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suppression Journal',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
