# Generated by Django 5.1.2 on 2026-06-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auditlogdeletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('admin', 'Administrateur'), ('responsable', 'Responsable de service'), ('employe', 'Employé')], default='employe', max_length=225),
        ),
    ]
