# Generated by Django 6.0.6 on 2026-07-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_utilisateur_email_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
