# Generated by Django 6.0.6 on 2026-07-06 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_file_original_name_folder_original_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRenameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_name', models.CharField(max_length=255)),
                ('new_name', models.CharField(max_length=255)),
                ('renamed_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rename_history', to='api.file')),
                ('renamed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-renamed_at'],
            },
        ),
    ]
