# Generated by Django 6.0.6 on 2026-07-06 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_filerenamehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('file', 'Fichier'), ('folder', 'Dossier')], max_length=10)),
                ('item_id', models.IntegerField()),
                ('nom', models.CharField(max_length=255)),
                ('original_name', models.CharField(blank=True, max_length=255, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('folder_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('deleted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trash_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
    ]
