# Generated by Django 6.0.6 on 2026-07-10 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_folder_deleted_at_folder_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
    ]
