# Generated by Django 6.0.6 on 2026-07-10 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_file_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folders', to=settings.AUTH_USER_MODEL),
        ),
    ]
