# Generated by Django 6.0.6 on 2026-07-11 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_folder_proprietaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
