# Generated by Django 6.0.6 on 2026-07-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_utilisateur_deleted_at_utilisateur_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='previous_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
