server {
    listen 80;
    client_max_body_size 5G;
    resolver 127.0.0.11 valid=30s;

    proxy_read_timeout    300s;
    proxy_send_timeout    300s;
    proxy_connect_timeout 300s;

    location /api/ {
        set $backend http://dmt-backend:8000;
        proxy_pass         $backend;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Expect            "";
    }

    location /django-admin/ {
        set $backend http://dmt-backend:8000;
        proxy_pass         $backend;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location /media/ {
        alias /app/media/;
    }

    location / {
        set $frontend http://dmt-frontend:80;
        proxy_pass         $frontend;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
    }
}
